export const APP_THEME_COLOR = '#081c2e';
export const APP_BACKGROUND_COLOR = '#1c75bc'
export const YELLOW_COLOR = '#fed41f'
export const WHITE_COLOR = '#FFF'
export const LINE_COLOR = 'rgba(255, 255, 255, 0.3)'
export const NAVIGATION_BAR_COLOR = '#061626';
export const NAVIGATION_BAR_TITLE_COLOR = '#FFF';
export const TRANSPARENT_COLOR = 'transparent'
export const PLACEHOLDER_COLOR = "#1865A3"
